name: WireGuard

on:
  workflow_dispatch:

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard

      - name: Generate config
        run: |
          umask 077
          wg genkey | tee privatekey | wg pubkey > publickey
          privkey=$(cat privatekey)
          pubkey=$(cat publickey)
          echo "[Interface]" > wg0.conf
          echo "PrivateKey = $privkey" >> wg0.conf
          echo "Address = 10.0.0.2/32" >> wg0.conf
          echo "" >> wg0.conf
          echo "[Peer]" >> wg0.conf
          echo "PublicKey = $pubkey" >> wg0.conf
          echo "Endpoint = github.com:51820" >> wg0.conf
          echo "AllowedIPs = 0.0.0.0/0" >> wg0.conf
          cat wg0.conf

      - name: Upload config as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-config
          path: wg0.conf
